[params]
user = "angel"
hostname = "hello.io"

showMetadata = false
showReadingTime = false
showPublishedDate = false

publishDir = "docs"

openLinksInNewTab = true

displayDateFormat = "2006-01-02"

  [params.author]
    name = "Angel Hormilla"
    email = "iabd4.angel.hormilla@gmail.com"
    avatarFirst = false

[[params.social]]
key = 0
name = "github"
url = "https://github.com/tu_usuario"

[[params.social]]
key = 1
name = "linkedin"
url = "https://www.linkedin.com/in/tu_usuario/"

[[params.social]]
key = 2
name = "curriculum"
url = "/files/curriculum.pdf"



[menu]
  [[menu.header]]
    name = "Sobre mí"
    url = "/sobre-mi/"
    weight = 1

  [[menu.header]]
    name = "Proyectos"
    url = "/proyectos/"
    weight = 2