[params]
user = "angel"
hostname = "hello.io"

openLinksInNewTab = true

displayDateFormat = "2006-01-02"

  [params.author]
    name = "Angel Hormilla"
    email = "iabd4.angel.hormilla@gmail.com"
    avatarFirst = false

[[params.social]]
key = 0
name = "github"
url = "hola.txt"

[[params.social]]
key = 1
name = "twitter"
url = "https://www.example.com"

[[params.social]]
key = 2
name = "mastodon"
url = "https://www.example.com"
rel = "me"  # You can also add rel to social link

[[params.social]]
key = 3
name = "email"
url = "mailto:email@example.com"



[menu]
  [[menu.header]]
    name = "Sobre mí"
    url = "/sobre-mi/"
    weight = 1

  [[menu.header]]
    name = "Proyectos"
    url = "/proyectos/"
    weight = 2